
GREEN_DESCRIPTION = "🟩 Green is the highest level of privileges (when the child is behaving well)."
YELLOW_DESCRIPTION = "🟨 Yellow is the next level (when the child is engaging in minor problem behaviors)."
RED_DESCRIPTION = "🟥 Red is the level on which the child is engaging in severe problem behaviors, such as a meltdown or aggressive behavior."

DESCRIPTION = GREEN_DESCRIPTION + "\n\n" + YELLOW_DESCRIPTION + "\n\n" + RED_DESCRIPTION + "\n\n"

GREEN_FEEDBACK = [
    "I am so incredibly proud of you for the wonderful behaviors you've been exhibiting lately. Your kindness, responsibility, and the effort you're putting into everything are truly remarkable. You make me proud every day with your actions and choices. Keep up the fantastic work, and know that I'm here to support you every step of the way. I love you!",
    "I am absolutely bursting with pride over the way you've been behaving recently. Your kindness, responsibility, and positive attitude are shining through, and it makes me so happy to see the person you're becoming. You're a wonderful child, and I feel truly blessed to be your mom. Keep up the excellent work, and remember that I'm here to cheer you on and support you every step of the way. I love you so much!",
    "My heart swells with pride when I see the amazing behaviors you've been showing. Your kindness, respect, and responsibility make me so proud to be your mom. Your choices and actions are a true reflection of the wonderful person you're becoming. Keep it up, and always remember that I'm here to support and encourage you every step of the way. I love you more than words can express!",
    "I am absolutely bursting with pride over the way you've been behaving recently. Your kindness, responsibility, and positive attitude are shining through, and it makes me so happy to see the person you're becoming. You're a wonderful child, and I feel truly blessed to be your mom. Keep up the excellent work, and remember that I'm here to cheer you on and support you every step of the way. I love you so much!",
    "I am beaming with pride at the way you've been showing such great behavior lately. Your kindness, responsibility, and positive attitude are shining through, and it warms my heart. I'm so proud of the person you're becoming, and I believe in you. Keep up the fantastic work, and remember that I'm here to support you every step of the way. I love you more than words can express!",
    "I want you to know just how proud I am of the amazing behaviors you've been showing lately. Your kindness, responsibility, and hard work don't go unnoticed. I'm overjoyed with the person you're becoming. Keep up the fantastic work, and remember that I'm always here to support and love you. I'm one proud mom!",
    "I am bursting with pride because of your recent behavior. Your kindness, responsibility, and the effort you've been putting in have not gone unnoticed. I can see you becoming a more wonderful person each day, and it warms my heart. Keep up the excellent work, my dear. I'm here to support and celebrate your successes with you. I love you so much!",
    "I want you to know just how proud I am of the excellent behaviors you've been showing. Your kindness, responsibility, and the way you've been handling things make me so happy. You're growing into a wonderful person, and it's a joy to see you making good choices. Keep it up, and remember that I'm here to support and love you every day.",
    "I just want to take a moment to tell you how proud I am of you. Your recent behavior and the good choices you've been making fill my heart with pride. Your kindness, responsibility, and your positive attitude are truly commendable. Keep up the great work, and remember, I'm always here to support you. I love you, and I'm excited to see you continue to grow and excel.",
    "Sweetheart, I want you to know how proud I am of you for the excellent behaviors you've been showing. Your kindness, responsibility, and the way you've been handling things is truly commendable. You're growing into such a wonderful and responsible young person, and it brings me so much joy to see you making these positive choices. Keep up the great work, and remember, I'm here to support you and celebrate your successes with you. I love you so much!"
]

YELLOW_FEEDBACK = [
    "Sweetie, I've noticed that you've been doing okay, but I believe you can do even better. I know you have the potential to excel and make great choices. Let's work together to improve your behavior and make positive changes. I have faith in you, and I'm here to support you every step of the way. You're capable of achieving so much, and I'm excited to see you reach your full potential.",
    "Darling, I've noticed that you've been handling things, well, not poorly, but perhaps not at your best. I know you have the potential to do even better. Let's talk about what might be getting in the way or if there's anything you need help with. I believe in you, and I know you can excel with a little more effort and focus. I'm here to support you every step of the way, and we can work together to bring out your best.",
    "Darling, I've noticed that you've been doing okay, but I believe you have the potential to do even better. I know you can make excellent choices and put in more effort in various areas. Let's work together to help you reach your full potential. I'm here to support you every step of the way, and I'm confident that with a little more focus, you can achieve great things.",
    "Darling, I've noticed that your behavior has been a bit in between lately. While you're not behaving poorly, I believe you have the potential to do even better. I know you can make more positive choices and exhibit good behaviors. Let's work together to understand what's going on and how we can improve things. I have faith in your ability to make great choices, and I'm here to support you every step of the way.",
    "I've noticed that you've been behaving lately, but I believe you can do even better. Let's talk about how we can work together to improve your behavior and make even more positive choices. I know you have the potential to excel, and I'm here to guide and support you every step of the way.",
    "Darling, I've noticed that you've been behaving, well, not poorly, but not as well as I know you can. I believe in your potential and your ability to make even better choices. Let's have a talk about what's been going on and how we can work together to improve your behavior. I know you can do it, and I'm here to support you every step of the way.",
    "Hey, I've noticed you've been doing okay, but I believe you can do even better. You have so much potential, and I know you can make better choices. Let's work together to improve and aim for the best. I'm here to support you in every way, and I know you can achieve more with a little extra effort. Keep going, and I'm sure you'll surprise yourself!",
    "Sweetie, I've noticed that you've been doing okay, but I believe you can do even better. I know you have the potential to make great choices and exhibit excellent behavior. Let's work together to improve and reach your full potential. I have faith in you, and I'm here to guide you every step of the way.",
    "Sweetie, I've noticed that your behavior has been somewhere in between lately. It's not necessarily bad, but it's also not quite meeting the expectations we have for you. I believe in your potential to do even better. Let's talk about what's going on, and how we can work together to improve your behavior and make choices that we can all be proud of. I know you're capable of it, and I'm here to support you in every way I can.",
    "Sweetie, I've noticed that you've been doing okay lately, but I believe you can do even better. I know you have a lot of potential, and I'm confident that you can make even more positive choices and improvements. Let's work together to set some goals and find ways to help you reach your full potential. I'm here to support you every step of the way, and I believe in your ability to do great things."
]

RED_FEEDBACK = [
    "I have to admit, I'm deeply disappointed in your recent behavior. It's not the way I raised you, and I know you're capable of so much better. I want to understand what's been going on and what's causing these problem behaviors. We need to work together to find a solution and get you back on the right track. I love you, and I believe in your ability to change and grow, but we have to address this issue.",
    "I can't help but feel a great deal of disappointment in your recent behavior. It's not what I expected from you, and I know you're more capable than this. We need to talk about what's been going on and what's causing these problem behaviors. I want to work with you to find a way to improve and make better choices. Remember, I'm here to support you, and I know you can do better.",
    "I have to be honest; I'm really disappointed with your recent behavior. I know you have so much potential, and these problem behaviors are not a reflection of the wonderful child I know you can be. Let's sit down and have a heart-to-heart talk about what's been going on. I'm here to help and guide you through this, but we need to address this issue together. I believe in your ability to change and make better choices.",
    "I'm really quite disappointed in your recent behavior. I've always believed in your potential and your ability to make good choices, but this isn't what I expected. We should have a conversation about what's been going on and why you've been exhibiting these problem behaviors. I want to work together with you to find a way to address this and help you become the best version of yourself. Remember, I love you and want the best for you.",
    "I'm really quite disappointed in your recent behavior. I've always believed in your potential and your ability to make good choices, but this isn't what I expected. We should have a conversation about what's been going on and why you've been exhibiting these problem behaviors. I want to work together with you to find a way to address this and help you become the best version of yourself. Remember, I love you and want the best for you.",
    "I'm feeling quite disappointed with the way you've been behaving lately. It's not in line with our family values, and I know you can do better. Let's have a heart-to-heart talk to understand what's causing these problem behaviors and how we can work together to address them. I want you to know that I believe in your potential, and I'm here to guide and support you through this.",
    "I'm truly disappointed in the way you've been behaving lately. I've always believed in your potential, and your recent actions don't reflect the values we've tried to instill in you. Let's have an open and honest conversation about what's going on and what's causing these behaviors. I'm here to help and guide you towards making better choices. I know you can rise above this and become the wonderful person I know you are capable of being.",
    "I want you to know that I'm really disappointed in the behavior I've been seeing from you lately. It's not what I believe you're capable of, and it's not in line with the values we've instilled in our family. We need to figure out what's causing these problem behaviors and work on finding a better way to handle them. I love you, and I know that you have the potential to make positive changes. Let's work together to make that happen.",
    "I must say, I'm quite disappointed with your recent behavior. It's not the child I know and love. We need to have a serious talk about what's going on and why you've been exhibiting these problem behaviors. I believe you have the potential to make better choices, and I'm here to help you through this. Let's work together to find a solution and get you back on the right path.",
    "I'm finding it quite disappointing to see you behaving this way. I know you have the potential to be a better person, and I have higher expectations for you. Let's have a conversation about what's driving these problem behaviors and figure out how we can address them together. I believe in your ability to change and grow, and I'm here to guide and support you through this."
]

